on: 
  push:
    branches:
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  main:
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo "$FB_KEY" > firebase_key.json
        shell: bash
        env:
          FB_KEY: ${{secrets.FB_KEY}}

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@main
        with:
          project: ${{ secrets.gcp_project }}
          deliverables: app.yaml
          credentials: ${{ secrets.gcp_credentials }}
